 export const brands = [
     "Astley Clarke", "Astrid Andersen", "AT KOLLEKTIVE", "Atelier Buffile", "Atlein",
     "ATP Atelier", "Atu Body Couture", "Au Départ", "Audemars Piguet", "Audo",
     "August Sandgren", "Auralee", "Aurelie Bidermann", "Automobili Lamborghini", "Autry",
     "Ava Adore", "Avant Toi", "AVAVAV", "Aviù", "Axel Arigato", "Aya Muse", "Ayda",
     "AYTM", "AZ FACTORY", "AZEEZA", "Azi.land", "Aztech Mountain", "AZZALIA", "Azzi & Osta",
     "B SIDES", "B-Low The Belt", "b+ab", "Ba&Sh", "Baccarat", "Backes & Strauss", "Bacon",
     "Badgley Mischka", "BAINA", "Baldinini", "Balenciaga", "Balenciaga Eyewear",
     "Balenciaga Pre-Owned", "Ballantyne", "Bally", "Balmain", "Balmain Eyewear",
     "Balmain Kids", "Balmain Pre-Owned", "Bambah", "Bang & Olufsen", "Bao Bao Issey Miyake",
     "Baobab Collection", "BAPY BY *A BATHING APE®", "Barba", "Barbara Bologna", "Barbara Bui",
     "Barbour", "Barbour International", "Barena", "Barrie", "BARROW", "Barton Perreira",
     "Baruni", "Baserange", "Bassike", "Batsheva", "Baum Und Pferdgarten", "Baume & Mercier",
     "Bazar Deluxe", "BAZZA ALZOUMAN", "BCBG Max Azria", "BearBrick", "Beatrice Di Borbone Vintage",
     "BEATRIZ PALACIOS", "BEC + BRIDGE", "Bell & Ross", "Bella Freud", "Belle Et Bon Bon",
     "Belstaff", "belysa", "BEMBIEN", "Benedetta Bruzziches", "Benjamin Benmoyal", "Bering",
     "Bernadette", "Bernardaud", "Bernhard Willhelm", "Bethany Williams", "BETTINA VERMILLON",
     "BETTTER", "Bevza", "Beyond Yoga", "Bialetti", "BIASIA", "Billionaire Boys Club",
     "Bimba y Lola", "BINIBAMBA", "BIRD & KNOLL", "birgitte herskind", "Birkenstock",
     "BITE Studios", "Bitossi Home", "Biyan", "Black Comme Des Garçons", "Black Coral",
     "BLACK SUEDE STUDIO", "BLACKSAW", "Blanca Vita", "Blancha", "Blancpain", "Blauer",
     "Blazé Milano", "Bloc Studios", "Blue Bird Shoes", "BLUE SKY INN", "BLUEMARBLE", "Blugirl",
     "Blumarine", "BODE", "Boglioli", "BOGNER", "BOGNER FIRE+ICE", "Bond-eye", "BONDI BORN",
     "Bonpoint", "Bonsai", "BONVO", "Bordallo Pinheiro", "Bordelle", "Borgo De Nor",
     "Boris Bidjan Saberi", "Borsalino", "Bosa", "BOSS", "BOTEH", "Both", "Bottega Veneta Eyewear",
     "Bottega Veneta Pre-Owned", "Botter", "Botto Giuseppe", "Boucheron Eyewear", "Bougeotte",
     "Boutique Moschino", "Boy Smells", "Boyarovskaya", "Boyish Jeans", "Boyy", "BRAND BLACK",
     "Brandon Maxwell", "Braun Watches", "Breguet", "Breitling", "Brigitte", "Briglia 1949",
     "Brioni", "Briston Watches", "Brock Collection", "Brøgger", "BROOKS", "Brunello Cucinelli",
     "Bruno Manetti", "Buben & Zorweg", "Buffalo", "Burberry", "Burberry Eyewear",
     "Burberry Pre-Owned", "Buttero", "Bvlgari", "Bvlgari Pre-Owned", "BY FAR",
     "By Malene Birger", "BYBORRE", "Byredo", "byTiMo", "C.P. Company", "C.P. Company Pre-Owned",
     "C2h4", "Cabana", "CAFÉ KITSUNÉ", "Cala de la Cruz", "Câllas Milano", "Calvin Klein",
     "Calvin Klein Jeans", "Calvin Klein Underwear", "Camila Klein", "Camilla", "Camper",
     "CamperLab", "Canada Goose", "Canadian Club", "Canali", "Cander", "CandleHand", "Canessa",
     "CANNARI CONCEPT", "Cappellini", "CAPRI POSITANO SANDALS", "Capsule Eleven", "Car Shoe",
     "Cara Cara", "Caran d'Ache", "CARAT* LONDON", "Caravana", "Carel Paris", "Carhartt WIP",
     "Carine Gilson", "Cariuma", "Carlo Moretti", "CARNE BOLLENTE", "Carolina Herrera",
     "Caroline Constas", "CAROLINE HU", "Carrera", "Cartier", "Cartier", "Cartier Eyewear",
     "Carven", "Carvil", "casa raki", "Casablanca", "Casadei", "Casey Casey", "Cashmere In Love",
     "Cassina", "Castañer", "Catherine Regehr", "CAVIA", "Cawley Studio", "Cazal", "Cecilia Prado",
     "Cecilie Bahnsen", "Celia B", "Celine Eyewear", "Céline Pre-Owned", "Celine Robert",
     "Cenere GB", "CFCL", "Champion", "CHANEL Pre-Owned", "Chantal Thomass", "Chaos",
     "Charles Jeffrey Loverboy", "Charlott", "Charlotte Chesnais", "Charlotte Olympia",
     "Charo Ruiz Ibiza", "Charriol", "Chaumet", "Chen Peng", "Cherevichkiotvichki", ]
 